name: 'sarif-results-to-runtask'
description: 'This code converts SARIF results to structured Terraform Cloud run task outputs'
author: 'gautambaghel'
branding:
  icon: 'shield'
  color: 'purple'

# Define your inputs here.
inputs:
  ngrok_domain:
    description: 'Ngrok domain'
    required: true

  ngrok_authtoken:
    description: 'Ngrok authorization token'
    required: true

  port:
    description: 'The port to forward traffic'
    required: false
    default: 3000

  runtask-hmac:
    description: 'The HMAC for the configured run task'
    required: false

# Define your outputs here.
outputs:
  runtask-output:
    description: 'Output JSON filename that will have the results from Terraform Cloud'
    value: ${{ steps.sarif-results-to-runtask.outputs.runtask-output }}

runs:
  using: "composite"
  steps:
    # Setup Ngrok.
    - run: docker run --net=host --detach -e NGROK_AUTHTOKEN=${{ inputs.ngrok_authtoken }} ngrok/ngrok:latest http --domain=${{ inputs.domain }} ${{ inputs.port }}
      shell: bash
    - uses: actions/setup-node@v3
      with:
        node-version: 20
    - id: sarif-results-to-runtask
      run: node dist/index.js &
      shell: bash
