name: 'The name of your action here'
description: 'Provide a description here'
author: 'Your name or organization here'

# Define your inputs here.
inputs:
  options:
    description: 'The URL for the configured run task'
    required: false

  runtask-hmac:
    description: 'The HMAC for the configured run task'
    required: false

# Define your outputs here.
outputs:
  runtask-output:
    description: 'Output JSON filename that will have the results from Terraform Cloud'

runs:
  using: node20
  main: dist/index.js
