name: 'The name of your action here'
description: 'Provide a description here'
author: 'Your name or organization here'

# Define your inputs here.
inputs:
  sarif-filename:
    description: 'Input SARIF filename that needs conversion to Terraform Cloud run task format'
    required: true

  runtask-filename:
    description: 'Output JSON filename that will have the results in Terraform Cloud run task format'
    required: false
    default: 'output.json'

  runtask-url:
    description: 'The URL for the configured run task'
    required: true

  runtask-hmac:
    description: 'The HMAC for the configured run task'
    required: true

# Define your outputs here.
outputs:
  runtask-filename:
    description: 'Your output description here'

runs:
  using: node20
  main: dist/index.js
